name: Wheels

on:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

jobs:
  build_wheel:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]

    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode version
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_SKIP: "*-musllinux* pp*"
          CIBW_TEST_COMMAND: "pytest -s {project}/tests/test.py"
          CIBW_TEST_REQUIRES: pytest
          MACOSX_DEPLOYMENT_TARGET: 11.00
          CIBW_BUILD_VERBOSITY: 2

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{matrix.os}}
          path: ./wheelhouse/*.whl

